#ifndef BIND_CORE_CONFIG 

// #define RECV_COPIER
#define SEND_COPIER
#define BENCHMARK_SEND_COPIER

#define RECV_COPIER_THREAD_CORE 2
#define SEND_COPIER_THREAD_CORE 2
#define IO_URING_THREAD_CORE 6
#define BENCH_SEND_THREAD_CORE 8

// #define NO_REDIRECT_COPY

#endif
